import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.scss";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/authOptions";
import { redirect } from "next/navigation";
import RightMenu from "../components/design/RightMenu";
import { ISession } from "../interfaces/ISession";
import Image from "next/image";

export const metadata: Metadata = {
  title: "کلاب آریا کیش",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: ISession | null = await getServerSession(authOptions);

  if (!session?.token) {
    return redirect("/login");
  }

  return (
    <>
      {console.log(session.result.firstname)}
      <div className="p-4 mt-4 mb-4 rounded-2xl bg-white mx-8">
        <div className="flex justify-between w-full items-center">
          <Image width={100} height={100} src="/logo.webp" />
          <div className="flex items-center gap-2">
            <span>
              {session.result.firstname} {session.result.lastname}
            </span>
            <span className="w-10 h-10 flex justify-center items-center bg-gray-200 rounded-full font-bold">
              {String(session.result.firstname).charAt(0)}{" "}
              {String(session.result.lastname).charAt(0)}
            </span>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-1 h-auto lg:h-full lg:grid-cols-12 md:px-8 px-4 md:gap-7">
        <div className="col-span-3">
          <RightMenu notificationCount={0} requestsCount={0} />
        </div>
        <div className="col-span-9">{children}</div>
      </div>
    </>
  );
}
