import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.scss";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/authOptions";
import { redirect } from "next/navigation";
import RightMenu from "../components/design/RightMenu";
import { ISession } from "../interfaces/ISession";
import ClientSessionProvider from "./ClientSessionProvider";
import Header from "./Header";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "کلاب آریا کیش",
  description: "Generated by create next app",
};

async function getData(session) {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_BASE_URL}/v1/api/core/user/permissions/isAccess/gs.admin.cartables.getall`,
    {
      headers: {
        Authorization: `Bearer ${session?.token}`,
      },
    }
  );
  const data = await res.json();
  return data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: ISession | null = await getServerSession(authOptions);
  const { result: hasPermission } = await getData(session);

  if (!session?.token) {
    return redirect("/login");
  }

  return (
    <html dir="rtl" lang="fa">
      <body>
        <ClientSessionProvider session={session}>
          <Suspense fallback={<div>در حال بارگذاری...</div>}>
            <Header hasPermission={hasPermission} />
          </Suspense>
          <div className="grid grid-cols-1 h-auto lg:h-full lg:grid-cols-12 md:px-8 px-4 md:gap-7">
            <div className="col-span-3">
              <RightMenu notificationCount={0} requestsCount={0} />
            </div>
            <div className="col-span-9">{children}</div>
          </div>
        </ClientSessionProvider>
      </body>
    </html>
  );
}