import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.scss";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/authOptions";
import { redirect } from "next/navigation";
import RightMenu from "../components/design/RightMenu";
import { ISession } from "../interfaces/ISession";

export const metadata: Metadata = {
  title: "کلاب آریا کیش",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: ISession | null = await getServerSession(authOptions);

  if (!session?.token) {
    return redirect("/login");
  }

  return (
    <html lang="en" dir="rtl">
      <body>
        <div className="grid grid-cols-1 lg:grid-cols-12 px-8 gap-7 ">
          <div className="col-span-3">
            <RightMenu notificationCount={0} requestsCount={0} />
          </div>
          <div className="col-span-9">{children}</div>
        </div>
      </body>
    </html>
  );
}
